import comfy_annotations

NODE_CLASS_MAPPINGS = comfy_annotations.NODE_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = comfy_annotations.NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']